services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5173
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge